TYPE=VIEW
query=select `combined_access`.`manager_pin` AS `manager_pin`,`combined_access`.`manager_role` AS `manager_role`,`combined_access`.`PIN` AS `PIN`,`combined_access`.`EMPNAME` AS `EMPNAME`,`combined_access`.`DESIG` AS `DESIG`,`combined_access`.`JOBPOSITION` AS `JOBPOSITION`,`combined_access`.`DIVISION` AS `DIVISION`,`combined_access`.`SECTION` AS `SECTION`,`combined_access`.`Role` AS `Role`,`combined_access`.`Project` AS `Project` from (select `d`.`PIN` AS `manager_pin`,`d`.`Role` AS `manager_role`,`e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project` from (`training_program2`.`cat_employee` `d` join `training_program2`.`cat_employee` `e`) where `d`.`Role` = \'Director\' and `e`.`Project` = `d`.`Project` union all select `h`.`PIN` AS `manager_pin`,`h`.`Role` AS `manager_role`,`e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project` from (`training_program2`.`cat_employee` `h` join `training_program2`.`cat_employee` `e`) where `h`.`Role` = \'head\' and `e`.`DIVISION` = `h`.`DIVISION` union all select `sh`.`PIN` AS `manager_pin`,`sh`.`Role` AS `manager_role`,`e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project` from (`training_program2`.`cat_employee` `sh` join `training_program2`.`cat_employee` `e`) where `sh`.`Role` = \'Section Head\' and `e`.`SECTION` = `sh`.`SECTION` union all select `emp`.`PIN` AS `manager_pin`,`emp`.`Role` AS `manager_role`,`emp`.`PIN` AS `PIN`,`emp`.`EMPNAME` AS `EMPNAME`,`emp`.`DESIG` AS `DESIG`,`emp`.`JOBPOSITION` AS `JOBPOSITION`,`emp`.`DIVISION` AS `DIVISION`,`emp`.`SECTION` AS `SECTION`,`emp`.`Role` AS `Role`,`emp`.`Project` AS `Project` from `training_program2`.`cat_employee` `emp` where `emp`.`Role` = \'Employee\' or `emp`.`Role` is null or `emp`.`Role` = \'\') `combined_access`
md5=4eaf98669bc62a0d71cbb062a1267528
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001753174904200524
create-version=2
source=SELECT \n    manager_pin, manager_role, \n    PIN, EMPNAME, DESIG, JOBPOSITION, DIVISION, SECTION, Role, Project\nFROM (\n    -- Directors can see all in their project\n    SELECT \n        d.PIN as manager_pin, \n        d.Role as manager_role,\n        e.PIN, e.EMPNAME, e.DESIG, e.JOBPOSITION, e.DIVISION, e.SECTION, e.Role, e.Project\n    FROM cat_employee d\n    CROSS JOIN cat_employee e\n    WHERE d.Role = \'Director\' AND e.Project = d.Project\n    \n    UNION ALL\n    \n    -- Heads can see all in their division\n    SELECT \n        h.PIN as manager_pin, \n        h.Role as manager_role,\n        e.PIN, e.EMPNAME, e.DESIG, e.JOBPOSITION, e.DIVISION, e.SECTION, e.Role, e.Project\n    FROM cat_employee h\n    CROSS JOIN cat_employee e\n    WHERE h.Role = \'head\' AND e.DIVISION = h.DIVISION\n    \n    UNION ALL\n    \n    -- Section Heads can see all in their section\n    SELECT \n        sh.PIN as manager_pin, \n        sh.Role as manager_role,\n        e.PIN, e.EMPNAME, e.DESIG, e.JOBPOSITION, e.DIVISION, e.SECTION, e.Role, e.Project\n    FROM cat_employee sh\n    CROSS JOIN cat_employee e\n    WHERE sh.Role = \'Section Head\' AND e.SECTION = sh.SECTION\n    \n    UNION ALL\n    \n    -- Employees can only see themselves\n    SELECT \n        emp.PIN as manager_pin, \n        emp.Role as manager_role,\n        emp.PIN, emp.EMPNAME, emp.DESIG, emp.JOBPOSITION, emp.DIVISION, emp.SECTION, emp.Role, emp.Project\n    FROM cat_employee emp\n    WHERE emp.Role = \'Employee\' OR emp.Role IS NULL OR emp.Role = \'\'\n) combined_access
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `combined_access`.`manager_pin` AS `manager_pin`,`combined_access`.`manager_role` AS `manager_role`,`combined_access`.`PIN` AS `PIN`,`combined_access`.`EMPNAME` AS `EMPNAME`,`combined_access`.`DESIG` AS `DESIG`,`combined_access`.`JOBPOSITION` AS `JOBPOSITION`,`combined_access`.`DIVISION` AS `DIVISION`,`combined_access`.`SECTION` AS `SECTION`,`combined_access`.`Role` AS `Role`,`combined_access`.`Project` AS `Project` from (select `d`.`PIN` AS `manager_pin`,`d`.`Role` AS `manager_role`,`e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project` from (`training_program2`.`cat_employee` `d` join `training_program2`.`cat_employee` `e`) where `d`.`Role` = \'Director\' and `e`.`Project` = `d`.`Project` union all select `h`.`PIN` AS `manager_pin`,`h`.`Role` AS `manager_role`,`e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project` from (`training_program2`.`cat_employee` `h` join `training_program2`.`cat_employee` `e`) where `h`.`Role` = \'head\' and `e`.`DIVISION` = `h`.`DIVISION` union all select `sh`.`PIN` AS `manager_pin`,`sh`.`Role` AS `manager_role`,`e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project` from (`training_program2`.`cat_employee` `sh` join `training_program2`.`cat_employee` `e`) where `sh`.`Role` = \'Section Head\' and `e`.`SECTION` = `sh`.`SECTION` union all select `emp`.`PIN` AS `manager_pin`,`emp`.`Role` AS `manager_role`,`emp`.`PIN` AS `PIN`,`emp`.`EMPNAME` AS `EMPNAME`,`emp`.`DESIG` AS `DESIG`,`emp`.`JOBPOSITION` AS `JOBPOSITION`,`emp`.`DIVISION` AS `DIVISION`,`emp`.`SECTION` AS `SECTION`,`emp`.`Role` AS `Role`,`emp`.`Project` AS `Project` from `training_program2`.`cat_employee` `emp` where `emp`.`Role` = \'Employee\' or `emp`.`Role` is null or `emp`.`Role` = \'\') `combined_access`
mariadb-version=100432
