TYPE=VIEW
query=select `e`.`PIN` AS `PIN`,`e`.`PNO` AS `PNO`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`EDUCATION` AS `EDUCATION`,`e`.`EXPERIENCE` AS `EXPERIENCE`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Project` AS `Project`,`e`.`Role` AS `Role`,`jp`.`JobPos_Descrip` AS `JobPos_Descrip`,`jp`.`JobPos_Purpose` AS `JobPos_Purpose`,`jp`.`JobPos_EduReq` AS `JobPos_EduReq`,`jp`.`JobPos_ExpReq` AS `JobPos_ExpReq`,`jp`.`JobPos_Tools_Software` AS `JobPos_Tools_Software`,`jpc`.`job_areas` AS `job_areas`,`jpc`.`general_tasks` AS `general_tasks`,`jpc`.`technical_tasks` AS `technical_tasks`,`jpc`.`required_trainings` AS `required_trainings`,group_concat(distinct coalesce(`cat_acq`.`TrgDesc`,`eta`.`Acquired_Training`) separator \'; \') AS `acquired_trainings`,group_concat(distinct coalesce(`cat_miss`.`TrgDesc`,`emt`.`Missing_Training`) separator \'; \') AS `missing_trainings` from ((((((`training_program2`.`cat_employee` `e` left join `training_program2`.`cat_jobposition` `jp` on(`e`.`JOBPOSITION` = `jp`.`JobPosition`)) left join `training_program2`.`job_position_comprehensive` `jpc` on(`e`.`JOBPOSITION` = `jpc`.`JobPosition`)) left join `training_program2`.`employee_trainings_acquired` `eta` on(`e`.`PIN` = `eta`.`PIN`)) left join `training_program2`.`cat_alltrainings` `cat_acq` on(`eta`.`Acquired_Training` = `cat_acq`.`TrgCode`)) left join `training_program2`.`employee_missing_trainings` `emt` on(`e`.`PIN` = `emt`.`PIN`)) left join `training_program2`.`cat_alltrainings` `cat_miss` on(`emt`.`Missing_Training` = `cat_miss`.`TrgCode`)) group by `e`.`PIN`,`e`.`PNO`,`e`.`EMPNAME`,`e`.`DESIG`,`e`.`JOBPOSITION`,`e`.`EDUCATION`,`e`.`EXPERIENCE`,`e`.`DIVISION`,`e`.`SECTION`,`e`.`Project`,`e`.`Role`,`jp`.`JobPos_Descrip`,`jp`.`JobPos_Purpose`,`jp`.`JobPos_EduReq`,`jp`.`JobPos_ExpReq`,`jp`.`JobPos_Tools_Software`,`jpc`.`job_areas`,`jpc`.`general_tasks`,`jpc`.`technical_tasks`,`jpc`.`required_trainings`
md5=28fb047db6da4ef2b8909992a2ddc580
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001753174904530566
create-version=2
source=SELECT \n    e.PIN,\n    e.PNO,\n    e.EMPNAME,\n    e.DESIG,\n    e.JOBPOSITION,\n    e.EDUCATION,\n    e.EXPERIENCE,\n    e.DIVISION,\n    e.SECTION,\n    e.Project,\n    e.Role,\n    jp.JobPos_Descrip,\n    jp.JobPos_Purpose,\n    jp.JobPos_EduReq,\n    jp.JobPos_ExpReq,\n    jp.JobPos_Tools_Software,\n    jpc.job_areas,\n    jpc.general_tasks,\n    jpc.technical_tasks,\n    jpc.required_trainings,\n    GROUP_CONCAT(DISTINCT COALESCE(cat_acq.TrgDesc, eta.Acquired_Training) SEPARATOR \'; \') as acquired_trainings,\n    GROUP_CONCAT(DISTINCT COALESCE(cat_miss.TrgDesc, emt.Missing_Training) SEPARATOR \'; \') as missing_trainings\nFROM cat_employee e\nLEFT JOIN cat_jobposition jp ON e.JOBPOSITION = jp.JobPosition\nLEFT JOIN job_position_comprehensive jpc ON e.JOBPOSITION = jpc.JobPosition\nLEFT JOIN employee_trainings_acquired eta ON e.PIN = eta.PIN\nLEFT JOIN cat_alltrainings cat_acq ON eta.Acquired_Training = cat_acq.TrgCode\nLEFT JOIN employee_missing_trainings emt ON e.PIN = emt.PIN\nLEFT JOIN cat_alltrainings cat_miss ON emt.Missing_Training = cat_miss.TrgCode\nGROUP BY e.PIN, e.PNO, e.EMPNAME, e.DESIG, e.JOBPOSITION, e.EDUCATION, e.EXPERIENCE, \n         e.DIVISION, e.SECTION, e.Project, e.Role, jp.JobPos_Descrip, jp.JobPos_Purpose, \n         jp.JobPos_EduReq, jp.JobPos_ExpReq, jp.JobPos_Tools_Software, jpc.job_areas, \n         jpc.general_tasks, jpc.technical_tasks, jpc.required_trainings
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `e`.`PIN` AS `PIN`,`e`.`PNO` AS `PNO`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`EDUCATION` AS `EDUCATION`,`e`.`EXPERIENCE` AS `EXPERIENCE`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Project` AS `Project`,`e`.`Role` AS `Role`,`jp`.`JobPos_Descrip` AS `JobPos_Descrip`,`jp`.`JobPos_Purpose` AS `JobPos_Purpose`,`jp`.`JobPos_EduReq` AS `JobPos_EduReq`,`jp`.`JobPos_ExpReq` AS `JobPos_ExpReq`,`jp`.`JobPos_Tools_Software` AS `JobPos_Tools_Software`,`jpc`.`job_areas` AS `job_areas`,`jpc`.`general_tasks` AS `general_tasks`,`jpc`.`technical_tasks` AS `technical_tasks`,`jpc`.`required_trainings` AS `required_trainings`,group_concat(distinct coalesce(`cat_acq`.`TrgDesc`,`eta`.`Acquired_Training`) separator \'; \') AS `acquired_trainings`,group_concat(distinct coalesce(`cat_miss`.`TrgDesc`,`emt`.`Missing_Training`) separator \'; \') AS `missing_trainings` from ((((((`training_program2`.`cat_employee` `e` left join `training_program2`.`cat_jobposition` `jp` on(`e`.`JOBPOSITION` = `jp`.`JobPosition`)) left join `training_program2`.`job_position_comprehensive` `jpc` on(`e`.`JOBPOSITION` = `jpc`.`JobPosition`)) left join `training_program2`.`employee_trainings_acquired` `eta` on(`e`.`PIN` = `eta`.`PIN`)) left join `training_program2`.`cat_alltrainings` `cat_acq` on(`eta`.`Acquired_Training` = `cat_acq`.`TrgCode`)) left join `training_program2`.`employee_missing_trainings` `emt` on(`e`.`PIN` = `emt`.`PIN`)) left join `training_program2`.`cat_alltrainings` `cat_miss` on(`emt`.`Missing_Training` = `cat_miss`.`TrgCode`)) group by `e`.`PIN`,`e`.`PNO`,`e`.`EMPNAME`,`e`.`DESIG`,`e`.`JOBPOSITION`,`e`.`EDUCATION`,`e`.`EXPERIENCE`,`e`.`DIVISION`,`e`.`SECTION`,`e`.`Project`,`e`.`Role`,`jp`.`JobPos_Descrip`,`jp`.`JobPos_Purpose`,`jp`.`JobPos_EduReq`,`jp`.`JobPos_ExpReq`,`jp`.`JobPos_Tools_Software`,`jpc`.`job_areas`,`jpc`.`general_tasks`,`jpc`.`technical_tasks`,`jpc`.`required_trainings`
mariadb-version=100432
