TYPE=VIEW
query=select `e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project`,`e`.`EDUCATION` AS `EDUCATION`,`e`.`EXPERIENCE` AS `EXPERIENCE`,`jp`.`JobPos_Purpose` AS `JobPos_Purpose`,`jp`.`JobPos_EduReq` AS `JobPos_EduReq`,`jp`.`JobPos_ExpReq` AS `JobPos_ExpReq`,`jp`.`JobPos_Tools_Software` AS `JobPos_Tools_Software`,coalesce(`req_count`.`required_trainings`,0) AS `total_required_trainings`,coalesce(`acq_count`.`acquired_trainings`,0) AS `total_acquired_trainings`,coalesce(`miss_count`.`missing_trainings`,0) AS `total_missing_trainings`,case when coalesce(`req_count`.`required_trainings`,0) = 0 then 100 else round(coalesce(`acq_count`.`acquired_trainings`,0) * 100.0 / `req_count`.`required_trainings`,2) end AS `training_completion_percentage` from ((((`training_program2`.`cat_employee` `e` left join `training_program2`.`cat_jobposition` `jp` on(`e`.`JOBPOSITION` = `jp`.`JobPosition`)) left join (select `training_required_by_jobposition`.`JobPosition` AS `JobPosition`,count(0) AS `required_trainings` from `training_program2`.`training_required_by_jobposition` group by `training_required_by_jobposition`.`JobPosition`) `req_count` on(`e`.`JOBPOSITION` = `req_count`.`JobPosition`)) left join (select `employee_trainings_acquired`.`PIN` AS `PIN`,count(0) AS `acquired_trainings` from `training_program2`.`employee_trainings_acquired` group by `employee_trainings_acquired`.`PIN`) `acq_count` on(`e`.`PIN` = `acq_count`.`PIN`)) left join (select `employee_missing_trainings`.`PIN` AS `PIN`,count(0) AS `missing_trainings` from `training_program2`.`employee_missing_trainings` group by `employee_missing_trainings`.`PIN`) `miss_count` on(`e`.`PIN` = `miss_count`.`PIN`))
md5=f4a8c4035e419f5360bc020c9466673c
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001753174904303088
create-version=2
source=SELECT \n    e.PIN,\n    e.EMPNAME,\n    e.DESIG,\n    e.JOBPOSITION,\n    e.DIVISION,\n    e.SECTION,\n    e.Role,\n    e.Project,\n    e.EDUCATION,\n    e.EXPERIENCE,\n    jp.JobPos_Purpose,\n    jp.JobPos_EduReq,\n    jp.JobPos_ExpReq,\n    jp.JobPos_Tools_Software,\n    COALESCE(req_count.required_trainings, 0) as total_required_trainings,\n    COALESCE(acq_count.acquired_trainings, 0) as total_acquired_trainings,\n    COALESCE(miss_count.missing_trainings, 0) as total_missing_trainings,\n    CASE \n        WHEN COALESCE(req_count.required_trainings, 0) = 0 THEN 100\n        ELSE ROUND((COALESCE(acq_count.acquired_trainings, 0) * 100.0) / req_count.required_trainings, 2)\n    END as training_completion_percentage\nFROM cat_employee e\nLEFT JOIN cat_jobposition jp ON e.JOBPOSITION = jp.JobPosition\nLEFT JOIN (\n    SELECT JobPosition, COUNT(*) as required_trainings\n    FROM training_required_by_jobposition\n    GROUP BY JobPosition\n) req_count ON e.JOBPOSITION = req_count.JobPosition\nLEFT JOIN (\n    SELECT PIN, COUNT(*) as acquired_trainings\n    FROM employee_trainings_acquired\n    GROUP BY PIN\n) acq_count ON e.PIN = acq_count.PIN\nLEFT JOIN (\n    SELECT PIN, COUNT(*) as missing_trainings\n    FROM employee_missing_trainings\n    GROUP BY PIN\n) miss_count ON e.PIN = miss_count.PIN
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `e`.`PIN` AS `PIN`,`e`.`EMPNAME` AS `EMPNAME`,`e`.`DESIG` AS `DESIG`,`e`.`JOBPOSITION` AS `JOBPOSITION`,`e`.`DIVISION` AS `DIVISION`,`e`.`SECTION` AS `SECTION`,`e`.`Role` AS `Role`,`e`.`Project` AS `Project`,`e`.`EDUCATION` AS `EDUCATION`,`e`.`EXPERIENCE` AS `EXPERIENCE`,`jp`.`JobPos_Purpose` AS `JobPos_Purpose`,`jp`.`JobPos_EduReq` AS `JobPos_EduReq`,`jp`.`JobPos_ExpReq` AS `JobPos_ExpReq`,`jp`.`JobPos_Tools_Software` AS `JobPos_Tools_Software`,coalesce(`req_count`.`required_trainings`,0) AS `total_required_trainings`,coalesce(`acq_count`.`acquired_trainings`,0) AS `total_acquired_trainings`,coalesce(`miss_count`.`missing_trainings`,0) AS `total_missing_trainings`,case when coalesce(`req_count`.`required_trainings`,0) = 0 then 100 else round(coalesce(`acq_count`.`acquired_trainings`,0) * 100.0 / `req_count`.`required_trainings`,2) end AS `training_completion_percentage` from ((((`training_program2`.`cat_employee` `e` left join `training_program2`.`cat_jobposition` `jp` on(`e`.`JOBPOSITION` = `jp`.`JobPosition`)) left join (select `training_required_by_jobposition`.`JobPosition` AS `JobPosition`,count(0) AS `required_trainings` from `training_program2`.`training_required_by_jobposition` group by `training_required_by_jobposition`.`JobPosition`) `req_count` on(`e`.`JOBPOSITION` = `req_count`.`JobPosition`)) left join (select `employee_trainings_acquired`.`PIN` AS `PIN`,count(0) AS `acquired_trainings` from `training_program2`.`employee_trainings_acquired` group by `employee_trainings_acquired`.`PIN`) `acq_count` on(`e`.`PIN` = `acq_count`.`PIN`)) left join (select `employee_missing_trainings`.`PIN` AS `PIN`,count(0) AS `missing_trainings` from `training_program2`.`employee_missing_trainings` group by `employee_missing_trainings`.`PIN`) `miss_count` on(`e`.`PIN` = `miss_count`.`PIN`))
mariadb-version=100432
