TYPE=VIEW
query=select `jp`.`JobPosition` AS `JobPosition`,`jp`.`JobPos_Descrip` AS `JobPos_Descrip`,`jp`.`JobPos_Purpose` AS `JobPos_Purpose`,`jp`.`JobPos_EduReq` AS `JobPos_EduReq`,`jp`.`JobPos_ExpReq` AS `JobPos_ExpReq`,`jp`.`JobPos_Tools_Software` AS `JobPos_Tools_Software`,group_concat(distinct `ja`.`JobArea` separator \'; \') AS `job_areas`,group_concat(distinct `jgt`.`JobGTask` separator \'; \') AS `general_tasks`,group_concat(distinct `jtt`.`JobTTask` separator \'; \') AS `technical_tasks`,group_concat(distinct `trj`.`TrgDesc` separator \'; \') AS `required_trainings` from (((((((`training_program2`.`cat_jobposition` `jp` left join `training_program2`.`x_jobposition_jobarea` `xja` on(`jp`.`JobPosition` = `xja`.`JobPosition`)) left join `training_program2`.`cat_jobarea` `ja` on(`xja`.`JobAreaCode` = `ja`.`JobAreaCode`)) left join `training_program2`.`x_jobposition_jobgtask` `xjg` on(`jp`.`JobPosition` = `xjg`.`JobPosition`)) left join `training_program2`.`cat_jobgtask` `jgt` on(`xjg`.`JobGTaskCode` = `jgt`.`JobGTaskCode`)) left join `training_program2`.`x_jobposition_jobttask` `xjt` on(`jp`.`JobPosition` = `xjt`.`JobPosition`)) left join `training_program2`.`cat_jobttask` `jtt` on(`xjt`.`JobTTask` = `jtt`.`JobTTaskCode`)) left join `training_program2`.`training_required_by_jobposition` `trj` on(`jp`.`JobPosition` = `trj`.`JobPosition`)) group by `jp`.`JobPosition`,`jp`.`JobPos_Descrip`,`jp`.`JobPos_Purpose`,`jp`.`JobPos_EduReq`,`jp`.`JobPos_ExpReq`,`jp`.`JobPos_Tools_Software`
md5=f8fd2678b2cf5c743320ac8bc24d362d
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001753174904385775
create-version=2
source=SELECT \n    jp.JobPosition,\n    jp.JobPos_Descrip,\n    jp.JobPos_Purpose,\n    jp.JobPos_EduReq,\n    jp.JobPos_ExpReq,\n    jp.JobPos_Tools_Software,\n    GROUP_CONCAT(DISTINCT ja.JobArea SEPARATOR \'; \') as job_areas,\n    GROUP_CONCAT(DISTINCT jgt.JobGTask SEPARATOR \'; \') as general_tasks,\n    GROUP_CONCAT(DISTINCT jtt.JobTTask SEPARATOR \'; \') as technical_tasks,\n    GROUP_CONCAT(DISTINCT trj.TrgDesc SEPARATOR \'; \') as required_trainings\nFROM cat_jobposition jp\nLEFT JOIN x_jobposition_jobarea xja ON jp.JobPosition = xja.JobPosition\nLEFT JOIN cat_jobarea ja ON xja.JobAreaCode = ja.JobAreaCode\nLEFT JOIN x_jobposition_jobgtask xjg ON jp.JobPosition = xjg.JobPosition\nLEFT JOIN cat_jobgtask jgt ON xjg.JobGTaskCode = jgt.JobGTaskCode\nLEFT JOIN x_jobposition_jobttask xjt ON jp.JobPosition = xjt.JobPosition\nLEFT JOIN cat_jobttask jtt ON xjt.JobTTask = jtt.JobTTaskCode\nLEFT JOIN training_required_by_jobposition trj ON jp.JobPosition = trj.JobPosition\nGROUP BY jp.JobPosition, jp.JobPos_Descrip, jp.JobPos_Purpose, jp.JobPos_EduReq, jp.JobPos_ExpReq, jp.JobPos_Tools_Software
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `jp`.`JobPosition` AS `JobPosition`,`jp`.`JobPos_Descrip` AS `JobPos_Descrip`,`jp`.`JobPos_Purpose` AS `JobPos_Purpose`,`jp`.`JobPos_EduReq` AS `JobPos_EduReq`,`jp`.`JobPos_ExpReq` AS `JobPos_ExpReq`,`jp`.`JobPos_Tools_Software` AS `JobPos_Tools_Software`,group_concat(distinct `ja`.`JobArea` separator \'; \') AS `job_areas`,group_concat(distinct `jgt`.`JobGTask` separator \'; \') AS `general_tasks`,group_concat(distinct `jtt`.`JobTTask` separator \'; \') AS `technical_tasks`,group_concat(distinct `trj`.`TrgDesc` separator \'; \') AS `required_trainings` from (((((((`training_program2`.`cat_jobposition` `jp` left join `training_program2`.`x_jobposition_jobarea` `xja` on(`jp`.`JobPosition` = `xja`.`JobPosition`)) left join `training_program2`.`cat_jobarea` `ja` on(`xja`.`JobAreaCode` = `ja`.`JobAreaCode`)) left join `training_program2`.`x_jobposition_jobgtask` `xjg` on(`jp`.`JobPosition` = `xjg`.`JobPosition`)) left join `training_program2`.`cat_jobgtask` `jgt` on(`xjg`.`JobGTaskCode` = `jgt`.`JobGTaskCode`)) left join `training_program2`.`x_jobposition_jobttask` `xjt` on(`jp`.`JobPosition` = `xjt`.`JobPosition`)) left join `training_program2`.`cat_jobttask` `jtt` on(`xjt`.`JobTTask` = `jtt`.`JobTTaskCode`)) left join `training_program2`.`training_required_by_jobposition` `trj` on(`jp`.`JobPosition` = `trj`.`JobPosition`)) group by `jp`.`JobPosition`,`jp`.`JobPos_Descrip`,`jp`.`JobPos_Purpose`,`jp`.`JobPos_EduReq`,`jp`.`JobPos_ExpReq`,`jp`.`JobPos_Tools_Software`
mariadb-version=100432
